spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
    database: h2
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
